// Code generated by scripts/generate-server-i18n.mjs; DO NOT EDIT.

package main

type appLocalePreference string

const (
	localeZhCN           appLocale           = "zh-CN"
	localeEnUS           appLocale           = "en-US"
	sourceAppLocale      appLocale           = localeZhCN
	defaultAppLocale     appLocale           = localeEnUS
	autoLocalePreference appLocalePreference = "auto"
	preferenceZhCN       appLocalePreference = "zh-CN"
	preferenceEnUS       appLocalePreference = "en-US"
)

var supportedAppLocales = []appLocale{localeZhCN, localeEnUS}
